### PR TITLE
Fix spelling in README

### PR DESCRIPTION
**Pull request by SheepTester**
I may have interpreted certain parts incorrectly

### CODE REVIEW

**Comment by radioblahaj** [comment]
Do you Want to Join?

**Review by radioblahaj — CHANGES_REQUESTED** [review]
Add Also, 
Inquires? Email Us at aravnarula@aravnarula.com

**Comment by SheepTester** [comment]
Okay; you've already invited to this organisation, by the way.

**Comment by radioblahaj** [comment]
So, Can you join?

**Comment by SheepTester** [comment]
I have joined :)

**Comment by radioblahaj** [comment]
YAY!

**Pull request merged**
